### ISSUE TITLE
Não é possível baixar as imagens

### ISSUE THREAD

**Issue by brunogasparetto** [fluig/universo-trend-fluig-docker#1]
Tentei baixar as imagens, porém é necessário efetuar um login. Nesse caso eu usaria o comando "docker login" apontando para docker.fluig.com? O usuário e senha é o mesmo da área do cliente do Fluig? Tentei criar conta lá e só aceita e-mail da própria TOTVS. É assim mesmo?

**Comment by michelbertrand** [comment]
Bom dia Bruno,

As imagens não estão disponíveis. Ainda não está produtizado.

Se você for cliente da Plataforma, crie uma sugestão de melhoria para
"dockerizar" a Plataforma em:
https://centraldeatendimento.totvs.com/hc/pt-br/community/topics/360001353814-fluig-fluig-Identity-Identity
<https://www.google.com/url?q=https://centraldeatendimento.totvs.com/hc/pt-br/community/topics/360001353814-fluig-fluig-Identity-Identity&sa=D&source=hangouts&ust=1580841728144000&usg=AFQjCNHQEi7lGWAh6uvfoyEh-8kHrvahkg>


Obrigado,
Michel.





Em seg., 30 de mar. de 2020 às 09:25, Bruno Gasparetto <
notifications@github.com> escreveu:

**Comment by HorselessName** [comment]
Oi. Eu tomei a liberdade também da sua sugestão e fiz essa publicação com essa sugestão...
https://centraldeatendimento.totvs.com/hc/pt-br/community/posts/4417640966295-fluig-fluig-Identity-Identity-Sugestão-Criar-imagem-Fluig-para-Docker-dockerizar-o-Fluig-

Também tenho interesse em testar o Fluig em Docker.
Seria excelente para a comunidade! 

De uma olhada, veja o que acha.
E eu também não encontrei nenhum vídeo e nem nada desse evento de 2019, você tem algum link da transmissão dessa trend do Universo TOTVS?

**Comment by michelbertrand** [comment]
Olá, boa tarde Raul.

Não sou mais da TOTVS.

Sugiro entrar em contato com alguém do time do Fluig, pois aposto que
gostariam de encontrar devs interessados em contribuir com o produto.

O Bruno Kluever Koneski é coordenador de desenvolvimento no time do fluig.

Abraço,
Michel.



Em sex., 31 de dez. de 2021 às 12:34, Raul Chiarella <
***@***.***> escreveu:
